#!/bin/bash

echo "🔨 TokenForge - GitHub Repository Setup"
echo "======================================"
echo ""
echo "Follow these steps to create your public GitHub repository:"
echo ""
echo "1. Go to https://github.com/new"
echo ""
echo "2. Create a new repository with these settings:"
echo "   - Repository name: tokenforge"
echo "   - Description: Production-ready token creation platform for Ethereum, BSC, and Solana"
echo "   - Public repository ✓"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo ""
echo "3. After creating the repository, run these commands:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/tokenforge.git"
echo "   git push -u origin main"
echo ""
echo "4. Optional: Add topics to your repository:"
echo "   - blockchain"
echo "   - ethereum"
echo "   - solana"
echo "   - token-creation"
echo "   - web3"
echo "   - defi"
echo "   - smart-contracts"
echo ""
echo "5. Update the README.md with your actual URLs:"
echo "   - Replace 'yourusername' with your GitHub username"
echo "   - Update social media links if you create them"
echo ""
echo "Your repository is ready to be pushed! 🚀"