# This is a template file. DO NOT commit actual secrets to version control.
# Use a secret management tool like Sealed Secrets, External Secrets Operator, or HashiCorp Vault.

apiVersion: v1
kind: Secret
metadata:
  name: memecoingen-secrets
  namespace: memecoingen
type: Opaque
stringData:
  database-url: "postgresql://username:password@postgres:5432/memecoingen"
  redis-url: "redis://:password@redis:6379"
  ethereum-rpc-url: "https://eth-mainnet.g.alchemy.com/v2/YOUR_KEY"
  bsc-rpc-url: "https://bsc-dataseed.binance.org/"
  solana-rpc-url: "https://api.mainnet-beta.solana.com"
  coingecko-api-key: "YOUR_COINGECKO_API_KEY"
  etherscan-api-key: "YOUR_ETHERSCAN_API_KEY"
  bscscan-api-key: "YOUR_BSCSCAN_API_KEY"
  twitter-api-key: "YOUR_TWITTER_API_KEY"
  twitter-api-secret: "YOUR_TWITTER_API_SECRET"
  discord-webhook-url: "YOUR_DISCORD_WEBHOOK_URL"
  telegram-bot-token: "YOUR_TELEGRAM_BOT_TOKEN"
  sentry-dsn: "YOUR_SENTRY_DSN"
  stripe-secret-key: "YOUR_STRIPE_SECRET_KEY"
  stripe-webhook-secret: "YOUR_STRIPE_WEBHOOK_SECRET"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: memecoingen
  namespace: memecoingen
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/memecoingen-prod-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: memecoingen-role
  namespace: memecoingen
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: memecoingen-rolebinding
  namespace: memecoingen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: memecoingen-role
subjects:
- kind: ServiceAccount
  name: memecoingen
  namespace: memecoingen